export const GET_USER_BUDGET_REQUEST = "GET_USER_BUDGET_REQUEST";
export const GET_USER_BUDGET_SUCCESS = "GET_USER_BUDGET_SUCCESS";
export const GET_USER_BUDGET_FAIL = "GET_USER_BUDGET_FAIL";
export const GET_USER_BUDGET_RESET = "GET_USER_BUDGET_RESET";

export const CREATE_USER_BUDGET_REQUEST = "CREATE_USER_BUDGET_REQUEST";
export const CREATE_USER_BUDGET_SUCCESS = "CREATE_USER_BUDGET_SUCCESS";
export const CREATE_USER_BUDGET_FAIL = "CREATE_USER_BUDGET_FAIL";
