export const ADD_NEW_TRANSACTION_REQUEST = "ADD_NEW_TRANSACTION_REQUEST";
export const ADD_NEW_TRANSACTION_SUCCESS = "ADD_NEW_TRANSACTION_SUCCESS";
export const ADD_NEW_TRANSACTION_FAIL = "ADD_NEW_TRANSACTION_FAIL";
export const ADD_NEW_TRANSACTION_RESET = "ADD_NEW_TRANSACTION_RESET";
