export const ADD_NEW_TRANSACTION_REQUEST = "ADD_NEW_TRANSACTION_REQUEST";
export const ADD_NEW_TRANSACTION_SUCCESS = "ADD_NEW_TRANSACTION_SUCCESS";
export const ADD_NEW_TRANSACTION_FAIL = "ADD_NEW_TRANSACTION_FAIL";
export const ADD_NEW_TRANSACTION_RESET = "ADD_NEW_TRANSACTION_RESET";

export const GET_USER_TRANSACTIONS_REQUEST = "GET_USER_TRANSACTIONS_REQUEST";
export const GET_USER_TRANSACTIONS_SUCCESS = "GET_USER_TRANSACTIONS_SUCCESS";
export const GET_USER_TRANSACTIONS_FAIL = "GET_USER_TRANSACTIONS_FAIL";
export const GET_USER_TRANSACTIONS_RESET = "GET_USER_TRANSACTIONS_RESET";
