export const ADD_NEW_TRANSACTION_REQUEST = "ADD_NEW_TRANSACTION_REQUEST";
export const ADD_NEW_TRANSACTION_SUCCESS = "ADD_NEW_TRANSACTION_SUCCESS";
export const ADD_NEW_TRANSACTION_FAIL = "ADD_NEW_TRANSACTION_FAIL";
export const ADD_NEW_TRANSACTION_RESET = "ADD_NEW_TRANSACTION_RESET";

export const GET_USER_TRANSACTIONS_REQUEST = "GET_USER_TRANSACTIONS_REQUEST";
export const GET_USER_TRANSACTIONS_SUCCESS = "GET_USER_TRANSACTIONS_SUCCESS";
export const GET_USER_TRANSACTIONS_FAIL = "GET_USER_TRANSACTIONS_FAIL";
export const GET_USER_TRANSACTIONS_RESET = "GET_USER_TRANSACTIONS_RESET";

export const GET_TRANSACTION_ITEM_REQUEST = "GET_TRANSACTION_ITEM_REQUEST";
export const GET_TRANSACTION_ITEM_SUCCESS = "GET_TRANSACTION_ITEM_SUCCESS";
export const GET_TRANSACTION_ITEM_FAIL = "GET_TRANSACTION_ITEM_FAIL";
export const GET_TRANSACTION_ITEM_RESET = "GET_TRANSACTION_ITEM_RESET";

export const UPDATE_TRANSACTION_ITEM_REQUEST =
  "UPDATE_TRANSACTION_ITEM_REQUEST";
export const UPDATE_TRANSACTION_ITEM_SUCCESS =
  "UPDATE_TRANSACTION_ITEM_SUCCESS";
export const UPDATE_TRANSACTION_ITEM_FAIL = "UPDATE_TRANSACTION_ITEM_FAIL";
export const UPDATE_TRANSACTION_ITEM_RESET = "UPDATE_TRANSACTION_ITEM_RESET";

export const DELETE_TRANSACTION_ITEM_REQUEST =
  "DELETE_TRANSACTION_ITEM_REQUEST";
export const DELETE_TRANSACTION_ITEM_SUCCESS =
  "DELETE_TRANSACTION_ITEM_SUCCESS";
export const DELETE_TRANSACTION_ITEM_FAIL = "DELETE_TRANSACTION_ITEM_FAIL";
export const DELETE_TRANSACTION_ITEM_RESET = "DELETE_TRANSACTION_ITEM_RESET";
